#!/bin/sh

BRIGHTNESS_DIR="/sys/class/backlight/intel_backlight"

MAX_BRIGHTNESS=$(cat $BRIGHTNESS_DIR/max_brightness)

[ -z $MAX_BRIGHTNESS ] && "Could not read max brightness value from $BRIGHTNESS_DIR/max_brightness" && exit

if [ -z $1 ]
then
	printf "Enter brightness value (1-$MAX_BRIGHTNESS): " 
	read BRIGHTNESS
else
	BRIGHTNESS=$1
fi

[ -z $BRIGHTNESS ] && echo "Something went wrong. Exiting..." && exit

echo $BRIGHTNESS | sudo tee /sys/class/backlight/intel_backlight/brightness > /dev/null

