#!/bin/bash


if [[ $1 == "prod" ]]; then
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml $2
fi

if [[ $1 == "dev" ]]; then
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml $2
fi

