#!/bin/bash

cd ~/projects

PROJECT_NAME=$(ls | dmenu)

cd $PROJECT_NAME
st npm start &

if [[ -d "./server" ]]; then
	echo "server exists..."
	cd server
	st npm run dev & 
fi

# run vscode
cd ~/projects/$PROJECT_NAME 
code .

