#!/bin/bash

setxkbmap -layout us,ge -option grp:alt_shift_toggle
xwallpaper --zoom $WALLPAPER &
xinput --set-prop "12" "libinput Accel Speed" -0.5 # set trackball sensitivity
xset r rate 180 60 &
compton --no-fading-openclose &
/usr/bin/dunst &
slstatus &
