#!/bin/bash

export PATH="$PATH:/home/gabo/scripts:/snap/bin:/usr/sbin"

# set trackball sensitivity
xinput --set-prop "12" "libinput Accel Speed" -0.6

xset r rate 180 60 &
setxkbmap -layout us,ge -option grp:alt_shift_toggle
compton --no-fading-openclose &
slstatus &

#exec dwm
